name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Run a random script
      run: |
        ls
        uname -a
        pwd
    - name: get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
    - name: echo output
      run: |
        echo ${{ steps.getfile.outputs.files }}
    - name: Run sqlav
      run: |
        for i in ${{ steps.getfile.outputs.files }}; do
          if [[ "$i" = *.sqc ]]; then
            git show HEAD~1:${i} > ${i}_old;
            python .github/workflows/prepare_diff.py $i ${i}_old > diff.sqc
            cp diff.sqc $i
            rm ${i}_old;
            /home/spasic/Dropbox/sql2theory/code/sqlav.py --z3 $i --cursors 1 --la;
          fi ;
        done
