name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Run a random script
      run: |
        ls
        uname -a
        pwd
        echo "$GITHUB_WORKSPACE"
    - name: Run sqlav
      run: /home/spasic/Dropbox/sqc/svn/sqlc/code/sqlav.py 03_1.sqc  --cursors 1 --la
    - name: get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
	git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs
    - name: echo output
      run: |
        echo ${{ steps.getfile.outputs.files }}
