name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - uses: lots0logs/gh-action-get-changed-files@2.0.6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Run a random script
      run: |
        ls
        uname -a
        pwd
    - name: Run a script with an error
      run: ./run.sh
    - name: Run a script with an output
      run: cat 00_1.sqc
    - name: Run sqlav
      run: /home/spasic/Dropbox/sqc/svn/sqlc/code/sqlav.py 03_1.sqc  --cursors 10 --la
