name: CI

on:
  repository_dispatch:
    types: sqlav

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Run a random script
      run: |
        echo "${{ github.event.client_payload.text }}" > "${{ github.event.client_payload.filename }}_new"
        python .github/workflows/prepare_diff.py "${{ github.event.client_payload.filename }}_new" "${{ github.event.client_payload.filename }}" > diff.sqc
        /home/spasic/Dropbox/sqc/svn/sqlc/code/sqlav.py diff.sqc --cursors 1 --la;
