name: CI

on:
  repository_dispatch:
    types: sqlav

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Run a random script
      run: |
        ls
        uname -a
        pwd
        echo "${{ github.event.client_payload.text }}" > "${{ github.event.client_payload.filename }}_new"
